import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";


function Home() {
  const [search, setSearch] = useState('')
  const [data, setData] = useState()
  const show = () => {
    document.querySelector('.placeholder').style.top = '161px'
    document.querySelector('.placeholder').style.fontSize = '10px'
    document.querySelector(".placeholder").style.transition = "all 0.5s";
  };

  const handleSearch = () => {
    if (search == '') {
      alert('Không để trống')
    }
    else {
      fetch(
        `https://api.openweathermap.org/data/2.5/weather?q=${search}&appid=3970f20d573dcbcf95bbfe9f97963883`
      )
        .then((res) => res.json())
        .then((res) => setData(res));
    }

    setSearch('')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
      </Head>
      <div className={styles.body}>
        <h1 className={styles.title}><i className="fa-solid fa-cloud-sun"></i> Weather App</h1>
        <br /> <br />
        <div className={styles.head}>
          <small className="placeholder">Enter City</small>
          <input onMouseOver={show} type="text"
            onChange={e => setSearch(e.target.value)}
            value={search}
          />
          <button onClick={handleSearch}>Search</button>
        </div>
        {data == undefined || data.cod == 404 ? (<h1 style={{ marginLeft: 120, color: 'white' }}>City Err <i className="fa-regular fa-face-frown"></i></h1>) : (
          <div>
            <div className={styles.tt}>
              {data ? (<h3>{data.name},{data.sys.country}</h3>) : ('')}
              {data ? (<p>{new Date().toLocaleString('vi')}</p>) : ('')}
              {data ? (<h2>{(data.main.temp - 273.15).toFixed(2)} &deg; C</h2>) : ('')}
              {data ? (<h4>{data.weather[0].main}</h4>) : ('')}
            </div>

            <div className={styles.icon}>
              {data ? (<p><i className="fa-solid fa-eye"></i> {data.visibility} m</p>) : ('')}
              {data ? (<p><i className="fa-solid fa-wind"></i> {data.wind.speed} m/s</p>) : ('')}
              {data ? (<p><i className="fa-solid fa-temperature-low"></i>  {data.main.humidity}%</p>) : ('')}
            </div>
          </div>
        )}







      </div>
    </div>
  );
}

export default Home;
